# Generated by Django 2.2.6 on 2019-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigiintagerfield', models.BigIntegerField(default=0)),
                ('binaryfield', models.BinaryField(default=b'\xf0\xf1\xf2', max_length=100)),
                ('booleanfield', models.BooleanField(null=True)),
                ('charfield', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefield', models.DateField(auto_now_add=True, null=True)),
                ('datetimefield', models.DateTimeField(auto_now_add=True, null=True)),
                ('decimalfield', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('durationfield', models.DurationField(null=True)),
                ('emailfield', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(null=True, upload_to='uploads/')),
                ('filepathfield', models.FilePathField(max_length=200, null=True, path=None)),
                ('floatfield', models.FloatField(default=0)),
                ('imagefield', models.ImageField(null=True, upload_to='uploads/')),
                ('integerfield', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genericipaddressfield', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('nullbooleanfield', models.NullBooleanField()),
                ('positiveintegerfield', models.PositiveIntegerField(default=0)),
                ('positivesmallintegerfield', models.PositiveSmallIntegerField(default=0)),
                ('slugfield', models.SlugField(allow_unicode=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel5',
            fields=[
                ('smallintegerfield', models.SmallIntegerField(default=0)),
                ('textfield', models.TextField()),
                ('timefield', models.TimeField()),
                ('urlfield', models.URLField()),
                ('uuidfield', models.UUIDField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
